### ISSUE TITLE
Thumbnail images should all be the same size

### ISSUE THREAD

**Issue by seanwash** [ShaRay/Leaf-it-to-Me#3]
![image](http://cl.ly/image/1N3J321H2n2M/Image%202015-07-30%20at%207.44.43%20AM.png)

Might be helpful: http://www.cssbakery.com/2011/11/size-and-crop-image-using-css.html

**Comment by ShaRay** [comment]
image on upper left size was smaller than other 3 images at 17.78 x 11.85 so I resized it to match other 3 images at 17.78 x 13.33
